import { useContext, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import {
  getProtected,
  postLogout,
  postSignIn,
  postSignUp,
} from "../modules/auth/auth";
import { SessionContext } from "./_app";

const HARDCODED_USER = {
  email: "test@gmail.pl",
  password: "pass",
};

export type User = {
  id: number;
  email: string;
};

const Home: NextPage<{ user: User | null; isAuth: boolean }> = ({ isAuth }) => {
  const [state, setState] = useState<string[]>([]);
  const [isAuthData, setIsAuth] = useState<boolean>(!!isAuth);
  const ctx = useContext(SessionContext);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 style={{ color: isAuthData ? "green" : "red " }}>
          Is logged: {(!!isAuthData).toString()}
        </h1>

        <a href="http://localhost:4000/auth/github">
          <button>Github signIn</button>
        </a>
        <button
          onClick={() => {
            postSignUp(HARDCODED_USER);
          }}
        >
          Sign Up Email
        </button>

        <button
          onClick={async () => {
            postSignIn(HARDCODED_USER).then(() => {
              setIsAuth(true);
            });
          }}
        >
          Login
        </button>

        <button
          onClick={() => {
            postLogout().then(() => {
              setIsAuth(false);
            });
          }}
        >
          Logout
        </button>

        <button
          onClick={async () => {
            try {
              const body = await getProtected();
              setState(body.data);
            } catch (error) {
              setState(["missing", "access", "token"]);
            }
          }}
        >
          Protected
        </button>

        <ul>
          {state?.map((el) => (
            <li key={el}>{el}</li>
          ))}
        </ul>
      </main>
    </div>
  );
};

export default Home;
